# Generated by Django 4.0.3 on 2022-05-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
