# Generated by Django 4.0.3 on 2022-05-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(1, 'Diajukan'), (2, 'Diproses'), (3, 'Selesai')], default=1),
        ),
    ]
