# Generated by Django 4.0.3 on 2022-05-17 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto_1',
            field=models.ImageField(blank=True, null=True, upload_to='POST/sebelum/'),
        ),
        migrations.AddField(
            model_name='post',
            name='foto_2',
            field=models.ImageField(blank=True, null=True, upload_to='POST/sesudah/'),
        ),
        migrations.AddField(
            model_name='post',
            name='teknisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teknisi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
