# Generated by Django 4.0.3 on 2022-05-25 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
