# Generated by Django 4.0.3 on 2022-05-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foto_default',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='POST/sesudah/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='foto_1',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='POST/sebelum/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='foto_2',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='POST/sesudah/'),
        ),
    ]
