# Generated by Django 4.0.3 on 2022-05-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_foto_1_alter_post_foto_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='foto_1',
            field=models.ImageField(null=True, upload_to='POST/sebelum/'),
        ),
    ]
